### ISSUE TITLE
native_opt patch fail to apply

### ISSUE THREAD

**Issue by llde** [Frogging-Family/dxvk-tools#10]
compiling with native_opt= true in the updxvk.cfg fail to apply the  specific patchset.
Formats of build-win32.txt and build-win64.txt seems completly different

**Comment by Tk-Glitch** [comment]
The commit above is not exactly a fix, but it should have been removed ages ago so here we go!
Closing

**Comment by llde** [comment]
I  suggest to also remove for good the async patchset. It's unmaintained and break badly some d3d11 unity games and maybe others d3d11 titles. (I mean gpu lock level of bad)

**Comment by Tk-Glitch** [comment]
People are still requesting it constantly so, meh.. I have tried to get rid of it multiple times already you know :frog:
