### ISSUE TITLE
dxvk async patch out of date and failing to apply

### ISSUE THREAD

**Issue by hurricane-dorian** [Frogging-Family/dxvk-tools#18]
APPLYING PATCH ../DXVKBUILD/patches/dxvk-async.dxvkpatch
1 out of 5 hunks FAILED -- saving rejects to file src/dxvk/dxvk_context.cpp.rej
4 out of 4 hunks FAILED -- saving rejects to file src/dxvk/dxvk_graphics.cpp.rej
4 out of 4 hunks FAILED -- saving rejects to file src/dxvk/dxvk_graphics.h.rej
2 out of 2 hunks FAILED -- saving rejects to file src/dxvk/dxvk_pipemanager.h.rej

**Comment by Tk-Glitch** [comment]
We are not shipping that patch (it's downloaded from Sporif's repo who has been maintaining it for some time), so you'll need to wait for a rebase from https://github.com/Sporif/dxvk-async.
Also, if you're on Nvidia, you'll want *NOT* to use it anymore as it was made obsolete by dxvk master.

**Comment by Tk-Glitch** [comment]
Should be fixed as of https://github.com/Sporif/dxvk-async/commit/bed4b5d8f1437ded466db4b9cc41bfd11155d7ee
