### ISSUE TITLE
future `setup_dxvk.sh` removal

### ISSUE THREAD

**Issue by Blisto91** [Frogging-Family/dxvk-tools#20]
In future releases of dxvk the setup script won't be included anymore. Just as a quick fyi 🐸 

See https://github.com/doitsujin/dxvk/pull/3097

**Comment by Tk-Glitch** [comment]
Handled with https://github.com/Frogging-Family/dxvk-tools/commit/bdd689c656123c4895d3019085827c5e113494ab
