### ISSUE TITLE
dxvk failing to build

### ISSUE THREAD

**Issue by JooJooBee666** [Frogging-Family/dxvk-tools#6]
Ran TkgThingy and updated everything last week, but dxvk fails.  RManually ran updxvk build but same problem.  This same error also occurs when building proton-tkg.   Waited for a bit and ran another update, but still failing.  It feels like some missing headers but I'm really not sure what I'm missing here.  See attached failed build log.
I've confirmed DXVK is up to date, HEAD is currently at e79e8b90626de8c6e812cada8ca0548e37553f68

[failed log.txt](https://github.com/Frogging-Family/dxvk-tools/files/5612594/failed.log.txt)

Any help would be much appreciated.  Let me know if there are any additional logs/cfgs you need to see

**Comment by Tk-Glitch** [comment]
Your log looks empty, but it's likely the usual unmet dependency of mingw 8.0 (which is now mandatory to build dxvk). Non-rolling distros are only offering 7.0 as far as I could see. You can use mostlyportable as a workaround.

**Comment by JooJooBee666** [comment]
Yep, looks like you are right.  Ubuntu is always so damned slow when it comes to this shit.  I'm trying your mostlyportable now.

**Comment by JooJooBee666** [comment]
Still no luck.  Exact same errors.  Do I need to set more than CC environment variable?

**Comment by Tk-Glitch** [comment]
Yes. Actually you should remove CC env vars and use the option available in dxvk-tools .cfg files instead.

**Comment by JooJooBee666** [comment]
Confirmed this worked.  Thanks again :+1:
